### ISSUE TITLE
No additional Tab if media file is on Desktop

### ISSUE THREAD

**Issue by bitboy85** [linux-man/nemo-mediainfo-tab#6]
Hi,

i'm using Linuxmint 19 Cinnamon and installed this Addon.
There is no additional Media Info tab in file properties if the file is placed on the Desktop.

**Comment by linux-man** [comment]
Sorry, I can't replicate the issue. What's your Desktop path?

**Comment by seigneurfuo** [comment]
@linux-man I can't replicate the issue too. Works fine with Linux Mint 19 on a fresh-installed VM.

**Comment by bitboy85** [comment]
I have this issue on two machines running a german Version where Desktop is called "Schreibtisch".
There is a difference HOW the file is selected:
if i right click the file directly on the desktop and choose properties, the media info tab is missing.
If i open nemo, navigate to Schreibtisch and then right click the file, the media info tab is available.

**Comment by linux-man** [comment]
I guess there's something wrong with nemo-desktop, since the plugin works with nemo.
Can you try to run nemo-desktop from terminal to lookout for errors?
Do:
```
nemo -q
pkill nemo-desktop
```
Your desktop icons should disappear. Then:
```
nemo-desktop
```
Open properties and look for messages on terminal.
You return to normal state by closing terminal and doing ALT-F2 + nemo-desktop

**Comment by bitboy85** [comment]
Thanks, after a complete nemo restart it seems to work. First i used the restart button in the modules menu which is not enough.
